# Generated by Django 4.1.7 on 2023-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genres',
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(null=True, to='myapp.genres'),
        ),
    ]
